-- supabase/migrations/2026-05-21-cup-label-fortunes.sql
--
-- Precomputed fortune pool for in-store (Square POS) cup labels.
-- Replaces the synchronous DeepSeek call in src/lib/cup-label/fortune.ts.

CREATE TABLE IF NOT EXISTS public.cup_label_fortunes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  text text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.cup_label_random_fortunes(n int)
RETURNS TABLE(text text)
LANGUAGE sql
STABLE
AS $$
  SELECT text FROM public.cup_label_fortunes ORDER BY random() LIMIT n;
$$;

GRANT EXECUTE ON FUNCTION public.cup_label_random_fortunes(int) TO service_role;

-- 500 seed rows below. ON CONFLICT (text) DO NOTHING keeps the
-- migration replayable on a database that already has some lines.

INSERT INTO public.cup_label_fortunes (text) VALUES ('Steam from the cup writes letters in the air') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pearls cluster at the bottom like sleeping cats') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The straw finds its first pearl on its own') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Boba softens slowly, the way good ideas do') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tea remembers every minute spent steeping') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Each bubble carries a tiny sky inside') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The kettle hisses softly before it sings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Loose leaves swim like calligraphy in hot water') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The brewing pot keeps secrets between the leaves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A single tea leaf can change the whole cup') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Foam crowns the cup like winter on a hill') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cold brew teaches the rewards of long waiting') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pearls bounce when they hear good news') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The cup warms hands before warming hearts') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A teapot waits without ever growing impatient') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bubbles know more about rising than gravity does') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('First pour of the day always tastes brightest') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The straw whistles when the cup is nearly empty') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Green tea hums where black tea sings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Honey settles to the bottom and waits to surprise') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Milk meets tea like dusk meets sky') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pearls have learned how to keep cool under pressure') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The lid traps a small storm of aroma') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Loose-leaf tea breathes when given enough room') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The cup left half-finished is still keeping warm') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A tea ceremony fits inside a paper cup') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Boba never rushes itself, and neither must you') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steam carries the day''s first hello') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The strainer keeps what matters and lets the rest go') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Iced tea remembers the warmth it used to be') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A fresh brew makes ordinary mornings feel chosen') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pearls roll like marbles when the cup is shaken') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Hot water unlocks the song hidden in tea leaves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bubbles burst quietly and that is also music') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The cup holds more patience than it lets on') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tea poured slowly tastes truer than tea poured fast') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Straws have a way of finding the last good sip') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pearls float when they are ready, not before') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A warm teapot in winter is a private sun') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steam climbs in spirals, looking for the ceiling') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Light slants through morning windows like spilled honey') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The kettle clicks off and the house exhales') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Curtains breathe with whatever wind passes through') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soft light makes ordinary kitchens feel new') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A clean counter is the start of a kind hour') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mornings arrive whether or not the alarm agrees') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The kitchen wakes up one appliance at a time') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Birds outside have already started their daily round') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bowl of fruit looks brighter before noon') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Fresh laundry smells faintly of weather') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sunrise paints the wall a different colour each day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The fridge hums a song no one wrote down') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A cool floor under bare feet greets the morning honestly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The coffee maker speaks in steam and clicks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Toast pops up like a tiny daily applause') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sunlight on a wooden table feels almost edible') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mornings forgive yesterday without being asked') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The first cup waits while the day finds itself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slow mornings make for braver afternoons') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A window left open invites the world to breakfast') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The clock ticks more gently before nine') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Newspapers arrive smelling faintly of rain') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Dew on the railing reflects the whole sky') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Coffee and tea share a corner of the counter peacefully') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The doormat collects last night''s quiet stories') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A teacup left out overnight tells a new joke') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Garden snails leave silver maps on the path') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tomato vines smell like summer remembering itself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bees treat lavender like a favourite library') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The mint plant has plans bigger than its pot') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Roses open as slowly as they need to') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A single fig leaf can shade a whole conversation') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Basil rewards anyone who notices it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Apples ripen on their own clock, not yours') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The garden hose curls like a sleeping animal') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Marigolds throw small orange parties along the fence') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Strawberries hide under leaves out of politeness') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Compost takes its time becoming soil again') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Earthworms quietly rearrange the underground furniture') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A sunflower turns its head the way a child does') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pumpkin vines wander like curious children') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Rain finds the thirstiest pot first') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Seedlings keep their secrets close to the soil') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The garden gate squeaks a familiar welcome') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Lemons grow heavy and then choose to fall') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Climbing peas hold on with surprising ambition') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Frost makes the cabbage taste sweeter') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wild herbs grow wherever they decide to') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A robin in the yard counts as company') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pollen drifts wherever the breeze pleases') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cucumber leaves catch dew like tiny green bowls') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The vegetable bed wakes up before the cook does') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mushrooms appear overnight like silent guests') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The wind moves through bamboo with deliberate grace') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A cloud crossing the sun makes the room thoughtful') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Rain on a tin roof becomes its own conversation') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Snow falls quieter than people remember') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Autumn leaves leave on schedule but never reluctantly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Summer evenings stretch longer than honest clocks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wind shakes the trees awake every spring') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Fog softens edges the way patience softens days') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sunlight after rain has its own kind of brightness') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The first frost arrives without announcing itself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Storm clouds gather like friends comparing notes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Thunder rolls slowly when it knows it is alone') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A puddle holds the entire sky for an hour') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Winter mornings keep their voices low') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Spring arrives before the calendar admits it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Autumn smells like apples and woodsmoke shaking hands') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Hot afternoons make even shadows take a break') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A gentle drizzle suits thoughtful walks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wind moves cherry petals like confetti without a parade') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Frost paints leaves with careful silver edges') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Rainwater makes plants remember what they are') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The first snowflake commits, and the rest follow') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sun and rain often share an afternoon') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mist hides the hills until the hills are ready') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Long evenings make for slower suppers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A cool breeze can carry away three small worries') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Footsteps on gravel mark the rhythm of arriving') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old books smell like libraries dreaming') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A folded blanket waits without complaining') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bookshelves keep their voices to themselves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The hallway light hums a long-running tune') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bedside lamp keeps watch for the reader') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slippers know the way to the kitchen by memory') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Closed doors keep tiny weathers of their own') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Open windows let curiosity in along with the breeze') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A coatrack remembers what season it is') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The doormat counts visitors in soft thuds') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mirrors borrow whatever light passes by') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A houseplant in the corner conducts the room') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Photo frames hold weather from years ago') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Worn floorboards greet bare feet politely') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Linen curtains soften light without arguing with it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A clean glass on a shelf carries a small star') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wooden spoons remember every soup they have stirred') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A whistling kettle interrupts thoughts kindly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The cutting board wears its scars proudly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Salt and pepper share a table without quarrel') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bowl of lemons brightens the kitchen for free') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The radio in the corner remembers older songs') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A teapot left near the window collects sunlight') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soft slippers slow the whole house down') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Drawer handles polish themselves over years of use') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old chairs remember the shape of long talks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A kettle on the boil is the day''s small drumroll') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Footsteps in a hallway carry their own tempo') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Letters wait politely on the entry table') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wool socks on a cool morning fix many things') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A houseplant lifts the room without asking for credit') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The candle on the table conducts a slow choir') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A street at dawn belongs mostly to the birds') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cafe windows fog up before the first customer') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The bakery exhales bread into the morning air') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bench in the park keeps quiet company') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cyclists pass like small bright rumours') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The corner shop opens with a familiar bell') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sidewalk cracks grow tiny forests of their own') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Streetlights bow off duty just as the sun arrives') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Buses sigh at every stop, never bored') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bookshops smell faintly of paper and patience') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A laundromat hums like a content sea') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crosswalks count time aloud for everyone') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The library breathes more slowly than the street outside') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Trams travel on tracks of small accumulated routine') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old pavements wear the weather like good shoes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A neon sign flickers and finds itself again') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Buskers tune up before the crowd arrives') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bus shelters keep small commuters out of the rain') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Coffee shops measure the morning in steam') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The mail carrier nods to the same dog daily') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bridge over still water doubles the view') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('City pigeons gather like opinionated regulars') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bench slats keep a record of every reader') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The market wakes up box by box') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Lampposts remember the routes home for tired walkers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cobblestones speak softly under careful shoes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Storefronts brighten the street before noon') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A flower seller arranges colour with care') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Park gates open without ceremony every morning') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A piano in the next room turns evenings into rooms') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Music plays even when no one is listening') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A whistled tune carries down the hallway unattended') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Records crackle the way old friends laugh') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Drumbeats from a passing car borrow your heartbeat briefly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A choir warming up sounds like a kettle full of birds') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Flutes tease the air into dancing shapes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Violins describe seasons better than calendars') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Guitar strings remember every chord ever held') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The radio guesses your mood about half the time') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A song heard once becomes weather inside you') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bells ring on the hour like reliable friends') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Birds and traffic share the same morning composition') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cellos hum like patient grandfathers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A piano left untouched gathers stories anyway') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Drums know where the heartbeat lives') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A whistled chorus walks ahead of its whistler') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soft jazz suits late afternoons especially well') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A piano lesson next door makes the wall hum') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wind chimes translate the breeze into small bells') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A nearby choir warms the wall it leans against') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cassettes click with the rhythm of memory') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sheet music waits for hands that recognise it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A music box winds down into its own dream') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Headphones can turn a bus stop into a stage') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pencils last longer when held with intent') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A blank page is half an invitation already') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Notebooks fill themselves once you start them') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sharp scissors do their job without comment') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The eraser keeps its opinions to itself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Paint mixes new colours by accident worth keeping') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crayons remember every birthday they survived') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A camera catches what eyes almost missed') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Postcards travel further than the people who write them') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Calligraphy brushes hold their breath between strokes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A sketchbook keeps company without ever interrupting') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Watercolour spreads where it pleases and is forgiven') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Inkwells smell faintly of midnight and ideas') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A glue stick keeps small inventions together') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A length of yarn becomes whatever the hands decide') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Knitting needles count rows like seconds') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A camera shutter blinks at things worth remembering') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Glitter escapes once and lives in the carpet forever') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A typewriter still makes the truest clack') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Paper folds into birds without forgetting paper') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Origami creases hold instructions for the next try') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Brushes wash themselves cleaner each session') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crayon scribbles often outlast careful drawings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pens find the right word eventually') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A sketch left half-finished can still be company') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Walking past the bakery slows even brisk shoes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A long walk untangles thoughts kindly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bare feet on warm tiles teach a quiet lesson') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Standing still for ten breaths counts as moving forward') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stretching in the morning unfolds the day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A short sit by the window adjusts the whole house') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Watching clouds counts as productive on the right day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Closing your eyes for a minute brightens the next hour') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening fully is the most generous skill') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Reading one page restores more than it spends') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slow chewing teaches the food what it tastes of') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The right pause sounds like a small accomplishment') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A walk after dinner adds a chapter to the day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Breathing out longer than in resets the whole room') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sipping water in winter thanks the body slowly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A clean breath in a quiet room counts as travel') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sitting on the porch costs nothing and pays well') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stretching at noon is a way of forgiving the desk') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening to silence is listening to many small things') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slow walking turns familiar streets into new ones') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pause at the door before stepping in is wisdom') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Calm hands make even hurried tasks gentle') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Eating with both hands free counts as luxury') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Watching tea steep slows the clock politely') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Standing in the garden barefoot grounds the day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Closing one tab clears more than the screen') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Breathing room is something you can give yourself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A short nap counts as repairs, not laziness') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sitting under a tree counts as conversation with it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A long exhale puts the room in order') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Watching the sky often is the same as travelling') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tying shoes carefully sets the day off well') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A drink of water counts as kindness to yourself') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stepping outside reshuffles every thought waiting at the door') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening to rain costs less than therapy') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A walk in mismatched weather still counts') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tea breaks repair more than they cost') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Quiet hours have edges only you can feel') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A long stretch in the doorway pleases the whole spine') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Time outside the screen rebuilds nearer things') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Watching steam rise organises a busy mind') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A quiet hour stretches further than a noisy day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Looking up from the desk recalibrates the spine') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pauses are not wasted minutes; they are deposits') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Walking to nowhere in particular still arrives somewhere') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sitting with a hot drink rewires a tired afternoon') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening to wind in leaves is older than music') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stepping barefoot onto grass shortens many sentences') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A kind tone outlasts the words it carried') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Helping someone find their keys also finds your own') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Holding the door open counts as a ceremony') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Offering tea before questions softens any visit') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A patient ear can turn a hard day around') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sharing the last cookie sweetens both sides') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A thank-you said twice is never twice as much') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening before answering doubles the answer') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Quiet generosity travels further than loud kindness') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A warm welcome rearranges the room politely') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Patience offered to others returns wearing slippers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Small kindness rolls downhill and gathers more') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A handwritten note arrives heavier than email') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Offering the better chair speaks before words do') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Kind questions invite kind answers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A second helping shared makes the dish taste better') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening twice as long as speaking earns trust') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Holding a tired friend''s bag is friendship in action') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A kept promise warms whatever room it enters') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Helping with the dishes is half the visit') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Patience never runs out when shared gently') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soft words land softer than careful loud ones') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Carrying a neighbour''s groceries shortens the whole stairwell') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Smiles travel by reflection more than transmission') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A second chance offered freely doubles in value') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Putting the lid back on the jar counts as care') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Refilling the kettle for someone else is fluent kindness') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Saying hello first costs nothing and unlocks much') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A handwritten card waits patiently for years on a shelf') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Helping carry the umbrella keeps two friendships dry') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Patient questions make even tangles unravel themselves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The quiet act of folding laundry helps everyone') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Generous coffee pours fix half the meeting before it starts') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Listening with the phone face down is the new luxury') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A cat in a sunbeam invents new shapes of contentment') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Dogs greet rain with the enthusiasm humans owe everything') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sparrows squabble like small parliamentarians at the feeder') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A snail in no hurry still arrives at the leaf') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Foxes pass through gardens like rumours with paws') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bees rehearse circles around the lavender at dawn') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A goldfish in a bowl carries a small ocean inside it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crickets translate dusk into careful percussion') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A magpie in the lawn looks like a small judge') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Frogs remember the rain before it falls') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Ladybirds wear their dots like trusted maps') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Squirrels store more confidence than walnuts') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A heron stands still long enough to be a wise rumour') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Owls keep the hours that humans abandoned') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Geese travel as committees but arrive as families') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Hedgehogs make small thunder under autumn leaves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cats yawn at problems your calendar takes seriously') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A puppy learning stairs is also a tiny philosopher') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bumblebees treat lavender like the only word they know') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Fireflies turn summer evenings into slow constellations') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Possums conduct nightly inspections that no one requested') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A spider''s web at sunrise is a brief gallery') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cicadas remember every summer they have ever known') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A duck on a pond stays calmer than the pond') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Butterflies move as if every flower deserves a visit') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A barn cat keeps her own appointments') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crows leave gifts on windowsills as if running errands') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mice tiptoe through silence with great commitment') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Geese formation drawing is the oldest geometry on display') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pond keeps fish secrets even in winter') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bats stitch the dusk together with quiet thread') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Crickets fall silent only for the most polite footsteps') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Fox kits stumble out of sleep like rumpled commas') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A tortoise arrives where it intended, eventually') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Curiosity is the cheapest ticket to a better day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Surprises happen most often near doorways') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The right book opens to the right page if asked') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Notebooks tend to fall open at the page you needed') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Small wonders cluster around anyone who looks for them') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Discoveries lurk in the corners of familiar rooms') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Curiosity uses ordinary tools, mostly eyes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A new road and an old map share an honest argument') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Routine paths still hide unfamiliar windows') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The world rearranges itself slightly each morning') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A long detour often finds the better view') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wandering inside one''s own city counts as travel') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A familiar room rewards a second look') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The view from the bus stop changes every season') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A returned hello unlocks a small new street') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Curiosity prefers slippers to running shoes most days') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old paths show new footprints to attentive walkers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The quietest corner of a park hides the brightest bird') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A second glance often catches what hurry misses') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Familiar streets keep undiscovered windows for the patient') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A blue door on a grey street brightens the block') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The shortcut through the alley remembers everyone who finds it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wonder fits into pockets if you let it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Unfamiliar staircases lead to familiar feelings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A neighbour''s garden becomes the new continent') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Doors that creak announce their loyalty over years') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old keys still fit doors no one asks about') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The library shelf has more rooms than the library') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wandering with no plan invents the best plans') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A fresh notebook predicts weather only it can see') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Holding a warm mug is half a hug') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A sweater that fits right warms more than skin') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Comfort gathers in small worn things') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A favourite chair welcomes shoulders by name') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A quilt on cold knees rewrites the evening') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wool blankets remember the people they have warmed') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A bowl of soup is shelter you can drink') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steam from a bath softens the day''s edges') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Quiet rooms know when to dim themselves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old slippers are loyal in ways shoes never learn') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A familiar pillow listens better than most professionals') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A hot bath turns a long day into a short one') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A wool jumper outlasts most of the years it warms') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Warmth from a fireplace settles into the wood for weeks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A favourite mug improves whatever fills it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Reading lamps know how to keep careful company') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Throw blankets multiply mysteriously in winter') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A worn leather chair invites longer thoughts') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slipper socks count as plumbing for cold floors') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A patient bath warms the bones in their own time') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Mugs of cocoa carry rumours of past winters') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A second blanket usually makes the first one stronger') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soft pyjamas turn houses into temples briefly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A kind chair takes the day off your knees') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Hot porridge in winter is engineering and affection combined') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Warm bread from the oven turns Tuesday into Saturday') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A heated towel rewrites the morning') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The kettle and the radiator agree on Tuesdays') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A fire crackling outside the window doubles the inside') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old wool socks deserve their own retirement plan') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The simplest meal can still earn applause') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A peeled orange perfumes the entire room') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Toast and tea are the cheapest civilisation') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slow-cooked things forgive impatient cooks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A handful of berries brightens a plain breakfast') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Soup tastes better with someone else stirring') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bread dough rises while you sleep, like quiet ambition') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Sharing food doubles whatever was on the plate') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Roasted vegetables sing in their own oven choir') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The cookbook with the most stains is usually the truest') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A sandwich made for someone else tastes different') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Fresh herbs change a meal the way windows change a room') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Lemon zest perfumes a kitchen for days') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Apples baked with cinnamon are autumn distilled') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pinch of salt is half the recipe') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stews ripen overnight into better versions of themselves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cold leftovers can still be a celebration') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A boiled egg is breakfast with no excuses') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Dumplings stack like small parcels of patience') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Pancakes flip best when no one is watching closely') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Hot chocolate forgives an entire week if asked') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Honey on toast spells out a slow morning') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A wedge of cheese arrives wearing dignity') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The kitchen smells of the day''s intentions') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Salt and lemon argue and produce something kind') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pot of soup learns the room it cooks in') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Marmalade keeps January in a jar') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A loaf cooling on the counter is a household celebrity') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Cinnamon enters a room and rearranges it gently') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steam from a kettle writes one quick poem') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A page turned moves the day forward by one') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Patience builds rooms inside the day') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The slowest river still arrives at the sea') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Quiet effort accumulates into surprising buildings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Habits leave footprints on the way to becoming character') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steady hands finish what hurried hands abandon') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A daily small kindness compounds like savings') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Tiny progress still belongs in the ledger') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The path bends, and so the walker bends with it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Long projects deserve short cups of tea') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Showing up is most of the work') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Practice rewrites the muscle without telling the mind') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A modest goal kept beats a grand goal abandoned') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steady steps wear the road into a friend') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Today''s small effort is tomorrow''s quiet competence') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The same lake at sunrise teaches new things to old eyes') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Routine is the scaffolding under spontaneity') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steady breathing makes for steadier hands') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Daily walks lengthen the spine and the patience') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A small habit kept becomes a private architect') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The simple shelf, often dusted, lasts longest') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A short letter answered is better than a long letter promised') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The job finished poorly still ranks above the job not begun') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A page a day fills shelves over decades') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Many small kindnesses outweigh one large announcement') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Slow rivers carve the deepest valleys without rushing') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Steady effort hums quieter than excitement, and outlasts it') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pot watered each morning tells time better than clocks') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Routine afternoons store the energy spontaneous evenings spend') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Daily reading is exercise for invisible muscles') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A standing desk on Mondays repairs many Thursdays') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Long phone calls still warm the house in winter') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A pause between drafts often writes the best sentence') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Patient projects outlast the noise that surrounds them') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old tools rest comfortably in well-organised drawers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A row of jars on a shelf forms a small library') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Stationery drawers contain rumours of finished letters') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A wooden chair pulled to the window invites longer thinking') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The lampshade catches dust like a calm conscience') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A clean desk earns its first idea quickly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wall calendars wear quietly toward December') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A coffee table holds yesterday''s evening in still life') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bookmarks save more than pages') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old photographs collect dust politely on shelves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A welcome mat keeps secrets quieter than guests') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Doorframes carry the height marks of growing years') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Window seats invite slow afternoons without scolding') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The hallway clock keeps the building loyal to time') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A worn rug remembers every quiet step') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Bookends keep small parliaments of paperbacks orderly') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Houseplants tilt politely toward the morning light') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Lamps left on warm rooms more than they light them') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old wooden floors sing under polite footsteps') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A spice rack stands like a small library of weathers') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Coat hooks count their family by season') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A drawer of mismatched socks tells a friendly story') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Vases empty between bouquets keep their best selves') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Wall clocks tick more politely after dark') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A folded newspaper waits like a calm visitor') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Kitchen drawers settle into themselves over the years') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('The dish rack hums dry between meals') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('A spare blanket folded on the chair offers winter assurance') ON CONFLICT (text) DO NOTHING;
INSERT INTO public.cup_label_fortunes (text) VALUES ('Old recipes survive on stained index cards') ON CONFLICT (text) DO NOTHING;
